export const CHANNEL_NAME_EXAMPLES = [
  "Szukamy ludzi do serwera Minecraft",
  "Chętni do tripu do Chorwacji",
  "Mecz Real - Barcelona",
  "Chat Łowców Burz",
  "Ekipa do wspólnych psich spacerów",
  "Fani anime i mangi",
  "Książkowe wieczory",
  "Poranna kawa online",
  "Miłośnicy górskich wędrówek",
  "Grupa do planszówek",
  "Wspólne gotowanie online",
  "Biegacze z Warszawy",
  "Kreatywne DIY",
  "Motoryzacja bez tajemnic",
  "Fani Marvela",
  "Kącik ogrodnika",
  "Wędkarze z Mazur",
  "Miłośnicy kotów",
  "Pasjonaci fotografii",
  "Ekipa na rowery",
  "Wspólne oglądanie seriali",
  "Grupa do nauki hiszpańskiego",
  "Fani Formuły 1",
  "Kącik programistów",
  "Miłośnicy kawy",
  "Wspólne granie w CS:GO",
  "Ekipa na escape room",
  "Fani horrorów",
  "Wspólne spacery po lesie",
  "Grupa do nauki jogi",
  "Miłośnicy pizzy",
  "Kreatywne pisanie",
  "Fani Star Wars",
  "Ekipa na koncert The Weeknd",
  "Wspólne wyjścia do kina",
  "Miłośnicy zwierząt egzotycznych",
  "Grupa do nauki gry na gitarze",
  "Fani retro gier",
  "Ekipa na paintball",
  "Wspólne treningi fitness",
  "Miłośnicy astronomii",
  "Kącik podróżników",
  "Fani piłki nożnej",
  "Ekipa na kajaki",
  "Wspólne oglądanie meczów",
  "Miłośnicy sushi",
  "Grupa do nauki francuskiego",
  "Fani komiksów",
  "Ekipa na festiwale",
  "Wspólne bieganie",
  "Miłośnicy zwierząt domowych",
  "Kącik majsterkowicza",
  "Fani fantasy",
  "Ekipa na wycieczki rowerowe",
  "Wspólne gotowanie azjatyckie",
  "Miłośnicy podróży po Polsce",
  "Grupa do nauki programowania",
  "Fani muzyki rockowej",
  "Ekipa na planszówki",
  "Wspólne wyjścia na basen",
  "Miłośnicy psów",
  "Kącik filmowy",
  "Fani gier RPG",
  "Ekipa na wspólne zakupy",
  "Wspólne oglądanie anime",
  "Miłośnicy biegania",
  "Grupa do nauki angielskiego",
  "Fani motoryzacji",
  "Ekipa na wspólne wyjazdy",
  "Wspólne treningi siłowe",
  "Miłośnicy kawiarni",
  "Kącik podróżniczy",
  "Fani sportów zimowych",
  "Ekipa na wspólne grillowanie",
  "Wspólne wyjścia do teatru",
  "Miłośnicy zwierząt leśnych",
  "Grupa do nauki niemieckiego",
  "Fani muzyki elektronicznej",
  "Ekipa na wspólne biegi",
  "Wspólne oglądanie dokumentów",
  "Miłośnicy gier planszowych",
  "Kącik kulinarny",
  "Fani sportów wodnych",
  "Ekipa na wspólne spacery",
  "Wspólne wyjścia na imprezy",
  "Miłośnicy podróży zagranicznych",
  "Grupa do nauki włoskiego",
  "Fani muzyki klasycznej",
  "Ekipa na wspólne wycieczki",
  "Wspólne treningi biegowe",
  "Miłośnicy zwierząt egzotycznych",
  "Kącik fotograficzny",
  "Fani gier komputerowych",
  "Ekipa na wspólne wypady za miasto",
  "Wspólne oglądanie kabaretów",
  "Miłośnicy sportów drużynowych",
  "Grupa do nauki japońskiego",
  "Fani muzyki pop",
  "Ekipa na wspólne wyjścia do muzeum",
  "Miłośnicy jazdy na rolkach",
  "Ekipa na wspólne morsowanie",
  "Fani kuchni włoskiej",
  "Grupa do nauki chińskiego",
  "Wspólne wyjścia na stand-up",
  "Miłośnicy zwierząt wodnych",
  "Kącik podróży autostopem",
  "Fani gier karcianych",
  "Ekipa na wspólne ogniska",
  "Wspólne treningi crossfit",
  "Miłośnicy architektury",
  "Grupa do nauki rosyjskiego",
  "Fani muzyki jazzowej",
  "Ekipa na wspólne wyjścia do zoo",
  "Wspólne oglądanie musicali",
  "Miłośnicy sportów walki",
  "Kącik miłośników historii",
  "Fani gier logicznych",
  "Ekipa na wspólne wyjazdy w góry",
  "Wspólne wyjścia na kręgle",
  "Miłośnicy sztuki współczesnej",
  "Grupa do nauki portugalskiego",
  "Fani muzyki folkowej",
  "Ekipa na wspólne wyjścia na lody",
  "Wspólne treningi pilates",
  "Miłośnicy astronomii amatorskiej",
  "Kącik miłośników zwierząt domowych",
  "Fani gier strategicznych",
  "Ekipa na wspólne wyjścia do escape roomu",
  "Wspólne oglądanie kabaretów",
  "Miłośnicy sportów ekstremalnych",
  "Grupa do nauki szwedzkiego",
  "Fani muzyki indie",
  "Ekipa na wspólne wyjścia na gokarty",
  "Wspólne treningi zumby",
  "Miłośnicy literatury fantasy",
  "Kącik miłośników kawy speciality",
  "Fani gier planszowych dla dzieci",
  "Ekipa na wspólne wyjścia na koncerty jazzowe",
  "Wspólne oglądanie opery",
  "Miłośnicy sportów rakietowych",
  "Grupa do nauki norweskiego",
  "Fani muzyki reggae",
  "Ekipa na wspólne wyjścia na paintball",
  "Wspólne treningi boksu",
  "Miłośnicy literatury faktu",
  "Kącik miłośników zwierząt egzotycznych",
  "Fani gier komputerowych retro",
  "Ekipa na wspólne wyjścia na planszówki",
  "Wspólne oglądanie baletu",
  "Miłośnicy sportów motorowych",
  "Grupa do nauki greckiego",
  "Fani muzyki country",
  "Ekipa na wspólne wyjścia na basen",
  "Wspólne treningi jogi",
  "Miłośnicy literatury dziecięcej",
  "Kącik miłośników herbaty",
  "Fani gier mobilnych",
  "Ekipa na wspólne wyjścia na festiwale filmowe",
  "Wspólne oglądanie stand-upu",
  "Miłośnicy sportów drużynowych",
  "Grupa do nauki czeskiego",
  "Fani muzyki bluesowej",
  "Ekipa na wspólne wyjścia na ściankę wspinaczkową",
  "Wspólne treningi pływackie",
  "Miłośnicy literatury klasycznej",
  "Kącik miłośników zwierząt leśnych",
  "Fani gier VR",
  "Ekipa na wspólne wyjścia na karaoke",
  "Wspólne oglądanie spektakli teatralnych",
  "Miłośnicy sportów wodnych",
  "Grupa do nauki fińskiego",
  "Fani muzyki alternatywnej",
  "Ekipa na wspólne wyjścia na lodowisko",
  "Wspólne treningi taneczne",
  "Miłośnicy literatury podróżniczej",
  "Kącik miłośników win",
  "Fani gier edukacyjnych",
  "Ekipa na wspólne wyjścia na mecze siatkówki",
  "Wspólne oglądanie gal MMA",
  "Miłośnicy sportów zimowych",
  "Grupa do nauki koreańskiego",
  "Fani muzyki filmowej",
  "Ekipa na wspólne wyjścia na wystawy",
  "Wspólne treningi sztuk walki",
  "Miłośnicy literatury science fiction",
  "Kącik miłośników piwa kraftowego",
  "Fani gier przygodowych",
  "Ekipa na wspólne wyjścia na maratony filmowe",
  "Wspólne oglądanie transmisji sportowych",
  "Miłośnicy sportów siłowych",
  "Grupa do nauki duńskiego",
  "Fani muzyki metalowej",
  "Ekipa na wspólne wyjścia na degustacje",
  "Wspólne treningi biegów przełajowych",
  "Miłośnicy literatury młodzieżowej",
  "Kącik miłośników czekolady",
  "Fani gier ekonomicznych",
  "Ekipa na wspólne wyjścia na rejsy",
  "Wspólne oglądanie pokazów iluzjonistów",
  "Miłośnicy jazdy konnej",
  "Ekipa na wspólne wyjścia na squash",
  "Fani kuchni azjatyckiej",
  "Grupa do nauki arabskiego",
  "Wspólne wyjścia na planszówki dla dorosłych",
  "Miłośnicy zwierząt egzotycznych",
  "Kącik podróży rowerowych",
  "Fani gier sportowych",
  "Ekipa na wspólne wyjścia na gokarty",
  "Wspólne treningi kalisteniki",
  "Miłośnicy architektury wnętrz",
  "Grupa do nauki łaciny",
  "Fani muzyki ambient",
  "Ekipa na wspólne wyjścia na wystawy sztuki",
  "Wspólne oglądanie kabaretów na żywo",
  "Miłośnicy sportów deskorolkowych",
  "Kącik miłośników historii sztuki",
  "Fani gier zręcznościowych",
  "Ekipa na wspólne wyjścia na koncerty muzyki klasycznej",
  "Wspólne oglądanie operetek",
  "Miłośnicy sportów lotniczych",
  "Grupa do nauki esperanto",
  "Fani muzyki world music",
  "Ekipa na wspólne wyjścia na paintball laserowy",
  "Wspólne treningi stretchingu",
  "Miłośnicy literatury obyczajowej",
  "Kącik miłośników zwierząt gospodarskich",
  "Fani gier strategicznych online",
  "Ekipa na wspólne wyjścia na planszówki rodzinne",
  "Wspólne oglądanie musicali na żywo",
  "Miłośnicy sportów walki MMA",
  "Grupa do nauki niderlandzkiego",
  "Fani muzyki soul",
  "Ekipa na wspólne wyjścia na basen otwarty",
  "Wspólne treningi nordic walking",
  "Miłośnicy literatury przygodowej",
  "Kącik miłośników kawy z różnych stron świata",
  "Fani gier logicznych online",
  "Ekipa na wspólne wyjścia na koncerty jazzowe",
  "Wspólne oglądanie baletu na żywo",
  "Miłośnicy sportów motorowych off-road",
  "Grupa do nauki rumuńskiego",
  "Fani muzyki gospel",
  "Ekipa na wspólne wyjścia na ściankę wspinaczkową",
  "Wspólne treningi pilatesu",
  "Miłośnicy literatury dziecięcej i młodzieżowej",
  "Kącik miłośników herbaty ziołowej",
  "Fani gier planszowych strategicznych",
  "Ekipa na wspólne wyjścia na festiwale kulinarne",
  "Wspólne oglądanie stand-upu na żywo",
  "Miłośnicy sportów drużynowych amatorskich",
  "Grupa do nauki węgierskiego",
  "Fani muzyki disco",
  "Ekipa na wspólne wyjścia na lodowisko miejskie",
  "Wspólne treningi tańca towarzyskiego",
  "Miłośnicy literatury podróżniczej i reportażu",
  "Kącik miłośników win z różnych krajów",
  "Fani gier edukacyjnych dla dzieci",
  "Ekipa na wspólne wyjścia na mecze koszykówki",
  "Wspólne oglądanie gal bokserskich",
  "Miłośnicy sportów zimowych rekreacyjnych",
  "Grupa do nauki tureckiego",
  "Fani muzyki trance",
  "Ekipa na wspólne wyjścia na degustacje win",
  "Wspólne treningi biegów górskich",
  "Miłośnicy literatury młodzieżowej fantasy",
  "Kącik miłośników czekolady rzemieślniczej",
  "Fani gier ekonomicznych online",
  "Ekipa na wspólne wyjścia na rejsy żeglarskie",
  "Wspólne oglądanie pokazów iluzjonistów na żywo",
  "Miłośnicy sportów siłowych amatorskich",
  "Fani muzyki house",
  "Ekipa na wspólne wyjścia na maratony biegowe",
  "Wspólne treningi biegów ulicznych",
  "Miłośnicy literatury science fiction i fantasy",
  "Kącik miłośników piwa regionalnego",
  "Fani gier przygodowych online",
  "Ekipa na wspólne wyjścia na maratony filmowe tematyczne",
  "Wspólne oglądanie transmisji sportowych na żywo",
  "Miłośnicy sportów ekstremalnych wodnych",
  "Grupa do nauki hebrajskiego",
  "Fani muzyki punk",
  "Ekipa na wspólne wyjścia na degustacje piwa",
  "Wspólne treningi biegów przełajowych w lesie",
  "Miłośnicy literatury obyczajowej i romansów",
  "Kącik miłośników kawy alternatywnej",
  "Fani gier karcianych kolekcjonerskich",
  "Ekipa na wspólne wyjścia na koncerty plenerowe",
  "Wspólne oglądanie kabaretów telewizyjnych",
  "Miłośnicy sportów deskorolkowych miejskich",
  "Grupa do nauki litewskiego",
  "Fani muzyki dance",
  "Ekipa na wspólne wyjścia na festiwale muzyczne",
];